# 담화표지 기반 응집성 분석 규칙
discourse_markers:
  # 분석에 사용할 담화표지 목록
  list: 
    - "그러나"
    - "하지만"
    - "그렇지만"
    - "그런데"
    - "따라서"
    - "그러므로"
    - "결론적으로"
    - "한편"
    - "반면에"
    - "또한"
    - "그리고"
    - "즉"
    - "예를 들어"
    - "결국"
    - "먼저"
    - "다음으로"
    - "마지막으로"
  
  # 담화표지 빈도에 대한 이상적인 범위와 점수 가중치
  desired_range:
    min: 3      # 최소 권장 빈도
    max: 10     # 최대 권장 빈도
    weight: 0.4 # 최종 점수 계산 시 응집성 점수의 가중치

# TF-IDF 기반 통일성 분석 규칙
tfidf:
  top_n: 5      # 추출할 상위 키워드 개수
  min_df: 1     # 단어가 포함된 최소 문서(문장) 수
  weight: 0.6   # 최종 점수 계산 시 통일성 점수의 가중치

# 피드백 메시지 템플릿 (향후 확장용)
# 현재는 main.py에 하드코딩된 로직을 사용합니다.
feedback_templates:
  - condition: "scores['cohesion'] < 0.5"
    message: "담화표지가 부족하여 문장 연결이 약합니다. '그러나', '따라서'와 같은 표지를 적절히 사용해 보세요."
  - condition: "scores['coherence'] < 0.3"
    message: "글의 핵심 주제가 명확하지 않습니다. 키워드를 중심으로 내용을 다듬어보세요."
